### ISSUE TITLE
[Application Request] - PlexTraktSync

### ISSUE THREAD

**Issue by clivewalkden** [GhostWriters/DockSTARTer-Templates#42]
# Name of the application
PlexTraktSync

## GitHub
[PlexTraktSync](https://github.com/Taxel/PlexTraktSync)

## Docker Hub/GitHub Registry
https://github.com/Taxel/PlexTraktSync/pkgs/container/plextraktsync

### Additional context
PlexTraktSync features

- Media in Plex are added to Trakt collection
- Ratings are synced (if ratings differ, Trakt takes precedence)
- Watched status are synced (dates are not reported from Trakt to Plex)
- Liked lists in Trakt are downloaded and all movies in Plex belonging to that list are added
- Watchlists are synced
- You can edit the config file to choose what to sync
- None of the above requires a Plex Pass or Trakt VIP membership. Downside: Needs to be executed manually or via cronjob, can not use live data via webhooks.

Docker Compose docs config
```
version: '2'
services:
  plextraktsync:
    image: ghcr.io/taxel/plextraktsync
    command: sync
    container_name: plextraktsync
    restart: on-failure:2
    volumes:
      - ./config:/app/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Tallinn
```
