### ISSUE TITLE
wireguard override

### ISSUE THREAD

**Issue by nemchik** [GhostWriters/DockSTARTer-Templates#84]
Ref: https://github.com/GhostWriters/DockSTARTer.com/issues/128

Add wireguard override page

```yaml
wireguard:
    image: linuxserver/wireguard
    hostname: ${DOCKERHOSTNAME}
    ports:
    - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    container_name: wireguard
    cap_add:
    - NET_ADMIN
    - SYS_MODULE
    environment:
    - PGID=${PGID}
    - PUID=${PUID}
    - TZ=${TZ}
    - SERVERURL=auto #optional
    - SERVERPORT=51820 #optional
    - PEERS=1 #optional
    - PEERDNS=auto #optional
    - INTERNAL_SUBNET=10.13.13.0 #optional
    logging:
      driver: json-file
      options:
        max-file: ${DOCKERLOGGING_MAXFILE}
        max-size: ${DOCKERLOGGING_MAXSIZE}
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DOCKERCONFDIR}/wireguard:/config
    - /lib/modules:/lib/modules
```
